### PR TITLE
Fix input file format check

### PR DESCRIPTION
**Pull request by mpampana**
Now PotreeConverter does not crash anymore when the input file is not a ".las" or ".laz" file.

### CODE REVIEW

**Comment by jidebingfeng** [comment]
@mpampana how can i get the code of commit `7bb8ddc072ad2dd6268dcf3b5e975cbb8054ad73`

**Comment by jidebingfeng** [comment]
I got last code is  from 2018-08-17

**Comment by mpampana** [comment]
@jidebingfeng https://github.com/potree/PotreeConverter/tree/7bb8ddc072ad2dd6268dcf3b5e975cbb8054ad73

**Comment by jidebingfeng** [comment]
thanks!

**Comment by jjPlusPlus** [comment]
I'm using this now- I think we should merge this. PLY support in Potree is huge for us

**Comment by m-schuetz** [comment]
I'm getting this warning when I try to set the target to develop:

```Some commits from the old base branch may be removed from the timeline, and old review comments may become outdated.```

I have no idea what this means but I'll just try it out since PRs should always go against the develop branch.

**Comment by m-schuetz** [comment]
The relevant change seems to be ```return icompare(tstr, suffix);```, the other lines seem to be only about code style.
I'd be happy to accept this as a PR if you reduce it to this line. 
Thanks!

**Pull request closed without merging**
