### PR TITLE
Work around issue #265

### PR DESCRIPTION
**Pull request by bugdanov**
Revert to LAStools pre 1.4 version to work around issue #265

### CODE REVIEW

**Comment by bugdanov** [comment]
Sorry I'm tired, still segfaults

I did also checkout Potree commit b8c8df7914aa082ebd399798b8171ba96014bd17
Must try to use a more recent commit, and publish a new pull request...

**Comment by bugdanov** [comment]
mmh when reverting to PotreeConverter commit 981c0fdb95a280d1cc0100ed240890b0670018a9 I have some a compilation error with gcc-6.3 :
```
"/src/PotreeConverter/PotreeConverter/include/LASPointWriter.hpp:37:3: error: 'memset' is not a member of 'std'
   std::memset(&header, 0, sizeof(laszip_header));
   ^~~
"/src/PotreeConverter/PotreeConverter/include/LASPointWriter.hpp:38:3: error: 'strcpy' is not a member of 'std'
```
And ncluding 'cstring' instead of 'string.h' or prefixing calls with 'std::' doesn't help.

**Comment by bugdanov** [comment]
So for now my best workaround is using LAStools  commit 8065ce39d50d09907691b5feda0267279428e586 + PotreeConverter commit b8c8df7914aa082ebd399798b8171ba96014bd17 + gcc-4.9

**Comment by jidebingfeng** [comment]
@bugdanov I`m tired using `  LAStools commit 8065ce39d50d09907691b5feda0267279428e586 + PotreeConverter commit b8c8df7 + gcc-4.9`,but do`s not work

**Comment by bugdanov** [comment]
@jidebingfeng feel free to come with a better solution

**Pull request closed without merging**
